# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'myazureconnection'
    subscriptionId: 'bd873b23-6d54-43fb-9c81-8d6340aba3c9'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'mynewrecourcegroup_rg'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'